//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduFuture
{
    using Microsoft.VisualStudio.Services.Account;
    using System;
    using System.Collections;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.DirectoryServices.ActiveDirectory;
    using static DevExpress.XtraEditors.Mask.MaskSettings;
    using static Microsoft.VisualStudio.Services.Graph.GraphResourceIds;

    public partial class UsersdbEntities : DbContext
    {
        public UsersdbEntities()
            : base("name=UsersdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Domain> Domains { get; set; }
        public virtual DbSet<Queue> Quests { get; set; }
        public virtual DbSet<Users> User_q { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
